# Generated by Django 4.0 on 2021-12-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_reports_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
