# Generated by Django 4.0 on 2021-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_serviceupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='pdf_link',
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(null=True, upload_to='reports/', verbose_name=''),
        ),
    ]
