# Generated by Django 4.0 on 2021-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_report_pdf_link_alter_report_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userid',
            new_name='clientid',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
