# Generated by Django 4.0 on 2022-01-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0009_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Monthly Report'},
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('pdf', models.FileField(null=True, upload_to='quarterly-reports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
