# Generated by Django 4.0 on 2022-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_supportticket_alter_report_options_quarterlyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarterlyreport',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='pdf',
            field=models.FileField(null=True, upload_to='quarterlyreports/'),
        ),
    ]
