# Generated by Django 4.0 on 2022-03-02 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clientagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceupdate',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
